Use hash size as KSF output size, expose KSF parameters & salt in configuration
bytemare/opaque pull request #73
Opened 2024-11-05 00:09 UTC by DJAndries

A couple of changes to achieve interoperability with facebook/opaque-ke:

- Use the configured hash size as the KSF output size (it seems that the Rust library does this, not sure if it's mentioned in the draft)
- Allow configuration of KSF cost parameters & salt value

2024-12-29 03:05 UTC, bytemare requested changes

2024-12-29 03:05 UTC, bytemare commented on opaque.go
> +	}
```suggestion
	}
	
```

2024-12-29 03:05 UTC, bytemare commented on opaque.go
> +	if len(encoded) < confIdsLength+2 { // corresponds to the configuration length + 2-byte encoding of empty context
```suggestion
	if len(encoded) < confIdsLength+6 { // corresponds to the configuration length + 3*2-byte encoding of empty context and KSF parameters
```

2024-12-29 03:05 UTC, bytemare commented on opaque.go
> +	ctx, _, err := encoding.DecodeVector(encoded[confIdsLength:])
```suggestion
	ctx, offset, err := encoding.DecodeVector(encoded[confIdsLength:])
```

use the returned offset

2024-12-29 03:05 UTC, bytemare commented on opaque.go
> +	}
```suggestion
	offset += confIdsLength

	ksfEncodedParams, offsetKSF, err := encoding.DecodeVector(encoded[offset:])
	if err != nil {
		return nil, fmt.Errorf("decoding the ksf configuration parameters: %w", err)
	}

	offset += offsetKSF

	var ksfParams []int
	for i := 0; i < len(ksfEncodedParams); i += 4 {
		ksfParams = append(ksfParams, encoding.OS2IP(ksfEncodedParams[i:i+4]))
	}

	ksfSalt, _, err := encoding.DecodeVector(encoded[offset:])
	if err != nil {
		return nil, fmt.Errorf("decoding the ksf salt: %w", err)
	}

	if len(ksfSalt) == 0 {
		ksfSalt = nil
	}
```

we can use the offset argument returned by DecodeVector

2024-12-29 03:05 UTC, bytemare commented on tests/opaque_test.go
> -
I believe we should keep this error detection test.

2024-12-29 03:09 UTC, bytemare commented
Hi @DJAndries ! Thank you for this PR, this is an excellent contribution :)
I'm sorry the delay, I haven't had time to get to this earlier.

I left some comments for some minor code changes.
I also believe we should keep the `TestDeserializeConfiguration_InvalidContextHeader` test function, but it would need some adaptation.

2024-12-29 03:10 UTC, bytemare commented
Have you noticed other differences in Kevin's implementation that would be interesting to add here?

2025-04-29 00:43 UTC, DJAndries commented
Hey @bytemare , thanks for the feedback. @claucece and I made some changes, lmk what you think

> Have you noticed other differences in Kevin's implementation that would be interesting to add here?

Nothing that comes to mind, but I'll be sure to raise another PR if I find some :)

2025-04-30 01:20 UTC, bytemare commented
Hi @DJAndries and @claucece 👋  
Thank you for these modifications! There are some things missing, and doing a review online here wasn't practical so I tried (and failed) to add some modifications. Please see #96 . After that, I'll close #96

2025-05-02 09:53 UTC, bytemare commented
Hi @DJAndries 👋 
We'll also need to update the branch with what's going on on main. I think it would be easier if I could contribute to the branch directly. If you're ok with it, can you re-enable “Allow edits from maintainers”?

This would make it easier and we can merge quickly and publish a new version (very needed)

2025-05-02 12:56 UTC, claucece commented
@bytemare I just rebase it to main ;) Let me know if it looks good!

2025-05-02 13:26 UTC, bytemare commented
Modifications look good :) thank you @claucece 🙏 
We still need to:
- resolve the sign-off issue
- resolve conflicts with the main branch

2025-05-04 08:47 UTC, bytemare requested changes
This should fix the remaining deserialization, linting, and testing issues, with the exception of 3 things:
- a missing test to run the IdentityKSF.Parameterize
- setting and using the parameters and salt for KSF in a real run of the protocol
- update the go.sum file (`go mod tidy` locally)

2025-05-05 22:05 UTC, claucece commented
Thank you @bytemare ! In regards to:

> a missing test to run the IdentityKSF.Parameterize

I added a small test but this is non trivial as the majority of those functions are not exported (and should not be).

> setting and using the parameters and salt for KSF in a real run of the protocol

This is already done in 'toInternal' and elsewhere. Can you clarify what you mean by using them?

> update the go.sum file (go mod tidy locally)

done.

Additionally, are there more linters or tests that we need to address?

Thank you,

2025-05-05 23:11 UTC, bytemare commented
Thank you @claucece 🙏 

> I added a small test but this is non trivial as the majority of those functions are not exported (and should not be).

You test uses the default configuration, which uses Argon2id. What I meant was to set it to use the Identity function, but I suppose we can actually skip that since it's a no-op anyways.

> This is already done in 'toInternal' and elsewhere. Can you clarify what you mean by using them?

I'm not sure I remember what I meant by that 😅  Let's skip it.

I think that's it, we're good here. Now I just need to figure out why two of the actions don't run.

2025-05-05 23:18 UTC, bytemare approved these changes

2025-05-05 23:22 UTC, merged